- name: app setup 
  include_role:
      name: common    # calling common role folder 
      tasks_from: app-setup

- name: nodejs setup 
  include_role:
      name: common    # calling common role folder 
      tasks_from: nodjs   # automatically it will calls the files under tasks
   
- name: copy mongodb repo
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.shell: mongosh --host mongodb.narendaws-84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.narendaws-84s.site < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0

  
- name: systemd_service setup
  include_role:
      name: common    # calling common role folder 
      tasks_from: systemd.yaml   # in this daemon reload , service statrt and restart

# - name: Deployment
#   tags: 
#   - deployment
#   import_role:
#     name: common
#     tasks_from: deployment

  

      